parameters:


    viewer_helper.class: ViewerBundle\Component\Helper\ViewerHelper

    form.type.server_urls.class: ViewerBundle\Form\Type\ServerUrlsType
    form.type.viewer_urls.class: ViewerBundle\Form\Type\ViewerUrlsType

services:
    viewer_helper:
        class: %viewer_helper.class%
        arguments: [ @doctrine, @project_helper ]

    form.type.viewerurl:
        class: %form.type.viewer_urls.class%
        arguments: [ @viewer_helper ]
        tags:
            - { name: form.type, alias: viewer_urls }

    form.type.server_urls:
        class: %form.type.server_urls.class%
        arguments: [ @doctrine, @project_helper ]
        tags:
            - { name: form.type, alias: server_urls }
