Core\ProjectBundle\Entity\Domain:
    type: entity
    table: domain
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20
            unique: true
        label:
            type: string
            length: 50
        description:
            type: text
        logo:
            type: string
            length: 20
            nullable: true

    manyToMany:
        projects:
            targetEntity: Core\ProjectBundle\Entity\Project
            joinTable:
                name: project_domain
                joinColumns:
                    domain_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    project_id:
                        referencedColumnName: id