Core\ProjectBundle\Entity\Project:
    type: entity
    table: project
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            length: 20
            unique: true
        label:
            type: string
            length: 50
        description:
            type: text
        logo:
            type: string
            length: 20
            nullable: true

    manyToMany:
        domains:
            targetEntity: Core\ProjectBundle\Entity\Domain
            mappedBy: projects
            cascade: [ persist ]
#            joinTable:
#                name: project_domain
#                joinColumns:
#                    project_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    domain_id:
#                        referencedColumnName: id
