#core_admin_homepage:
#    path:     /
#    defaults: { _controller: CoreAdminBundle:Default:index }
#    requirements:
#        @site: admin
#    condition: "request.attributes.get('@site') == 'admin'"
