parameters:
    templating.globals.class: Core\LayoutBundle\Component\Templating\GlobalVariables
    tool_helper.class: Core\LayoutBundle\Component\Helper\ToolHelper
    breadcrumb_helper.class: Core\LayoutBundle\Component\Helper\BreadcrumbHelper
    url_helper.class: Core\LayoutBundle\Component\Helper\UrlHelper

    twig.extension.core.global.class: Core\LayoutBundle\Twig\GlobalExtension

services:
    tool_helper:
        class: %tool_helper.class%
        arguments: [ @service_container ]

    breadcrumb_helper:
            class: %breadcrumb_helper.class%
            arguments: [ @request_stack, @tool_helper, %breadcrumb.template% ]

    url_helper:
        class: %url_helper.class%

    twig.extension.core.global:
        class: %twig.extension.core.global.class%
        arguments: [ @breadcrumb_helper ]
        tags:
            - { name: twig.extension }
