core_project_admin:
    path:     /
    defaults: { _controller: CoreProjectBundle:Admin:projects }
    requirements:
        _site: admin


core_project_admin_project:
    path:     /{project}/
    defaults: { _controller: CoreProjectBundle:Admin:projects }
    requirements:
        _site: admin

core_project_homepage:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:index }

core_project_home:
    path:     /

core_project_project:
    path:     /{project}/
    defaults: { _controller: CoreProjectBundle:Default:indexProject }