core_project_admin_project_edit:
    path:     /
    defaults: { _controller: CoreProjectBundle:Admin:project, @domain: null }
    requirements:
        @siteaccess: admin
        @project: %

core_project_admin_project_add:
    path:     /newproject
    defaults: { _controller: CoreProjectBundle:Admin:project, @project: null, @domain: null }
    requirements:
        @siteaccess: admin

core_project_admin_domain_edit:
    path:     /
    defaults: { _controller: CoreProjectBundle:Admin:domain, @project: null }
    requirements:
        @siteaccess: admin
        @domain: %

core_project_admin_domain_add:
    path:     /newdomain/
    defaults: { _controller: CoreProjectBundle:Admin:domain, @project: null, @domain: null }
    requirements:
        @siteaccess: admin

core_project_admin:
    path:     /
    defaults:
        _controller: CoreProjectBundle:Admin:list
        @project: null
        @domain: null
    requirements:
        @siteaccess: admin

core_project_project:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:indexProject, @domain: null }
    requirements:
        @project: %

core_project_default:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:index }
