core_project_admin_project_edit:
    path:     /edit
    defaults: { _controller: CoreProjectBundle:Admin:project, @domain: null }
    requirements:
        @siteaccess: admin
        @project: %

core_project_admin_project_add:
    path:     /newproject
    defaults: { _controller: CoreProjectBundle:Admin:project, @project: null, @domain: null }
    requirements:
        @siteaccess: admin

core_project_admin_project_del:
    path:     /delete/{confirm}
    defaults: { _controller: CoreProjectBundle:Admin:delete, @domain: null, confirm: false }
    requirements:
        @siteaccess: admin
        @project: %

core_project_admin_domain_edit:
    path:     /edit
    defaults: { _controller: CoreProjectBundle:Admin:domain, @project: null }
    requirements:
        @siteaccess: admin
        @domain: %

core_project_admin_domain_add:
    path:     /newdomain
    defaults: { _controller: CoreProjectBundle:Admin:domain, @project: null, @domain: null }
    requirements:
        @siteaccess: admin

core_project_admin_domain_del:
    path:     /delete/{confirm}
    defaults: { _controller: CoreProjectBundle:Admin:delete, @project: null, confirm: false }
    requirements:
        @siteaccess: admin
        @domain: %

core_project_admin_daemon:
    path:     /daemons
    defaults: { _controller: CoreProjectBundle:AdminDaemon:list }
    requirements:
        @siteaccess: admin

core_project_admin_daemon_add:
    path:     /daemons/new
    defaults: { _controller: CoreProjectBundle:Admin:daemon, name: null }
    requirements:
        @siteaccess: admin

core_project_admin_daemon_edit:
    path:     /daemons/edit/{name}
    defaults: { _controller: CoreProjectBundle:Admin:daemon, name: null }
    requirements:
        @siteaccess: admin

core_project_admin_daemon_del:
    path:     /daemons/delete/{name}/{confirm}
    defaults: { _controller: CoreProjectBundle:Admin:daemonDelete, confirm: false }
    requirements:
        @siteaccess: admin

core_project_admin_link_add:
    path:     /daemons/links/new/{project}/{domain}/{daemon}
    defaults: { _controller: CoreProjectBundle:Admin:link, id: null, project: null, domain: null, daemon: null }
    requirements:
        @siteaccess: admin

core_project_admin_link_edit:
    path:     /daemons/links/edit/{id}
    defaults: { _controller: CoreProjectBundle:Admin:link, id: null }
    requirements:
        @siteaccess: admin

core_project_admin_link_del:
    path:     /daemons/links/delete/{id}/{confirm}
    defaults: { _controller: CoreProjectBundle:Admin:linkDelete, confirm: false }
    requirements:
        @siteaccess: admin

core_project_admin:
    path:     /
    defaults:
        _controller: CoreProjectBundle:Admin:list
        @project: null
        @domain: null
    requirements:
        @siteaccess: admin

core_project_project:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:indexProject, @domain: null }
    requirements:
        @project: %

core_project_domain:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:indexDomain }
    requirements:
        @domain: %

core_project_default:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:index }
