core_project_homepage:
    path:     /
    defaults: { _controller: CoreProjectBundle:Default:index }

core_project_project:
    path:     /{project}/
    defaults: { _controller: CoreProjectBundle:Project:index }
