parameters:
    router_listener.class: Core\ProjectBundle\EventListener\RouterListener
    router.options.generator_class: Core\ProjectBundle\Component\Routing\Generator\UrlGenerator
    router.options.generator_base_class: Core\ProjectBundle\Component\Routing\Generator\UrlGenerator

    project_helper.class: Core\ProjectBundle\Component\Helper\ProjectHelper

services:
    project_helper:
        class: %project_helper.class%
        arguments: [ @doctrine ]
