parameters:
    templating.globals.class: Core\ProjectBundle\Component\Templating\GlobalVariables
    router.options.generator_class: Core\ProjectBundle\Component\Routing\Generator\UrlGenerator
    router.options.generator_base_class: Core\ProjectBundle\Component\Routing\Generator\UrlGenerator

    event_subscriber.project.router.class: Core\ProjectBundle\EventSubscriber\RouterSubscriber
    project_helper.class: Core\ProjectBundle\Component\Helper\ProjectHelper
    daemon_helper.class: Core\ProjectBundle\Component\Helper\DaemonHelper

services:
    event_subscriber.project.router:
        class: %event_subscriber.project.router.class%
        arguments: [ @project_helper, @router, @?router.request_context ]
        tags:
            - { name: kernel.event_subscriber }

    project_helper:
        class: %project_helper.class%
        arguments: [ @request_stack, @doctrine ]

    daemon_helper:
            class: %daemon_helper.class%
            arguments: [ @request_stack, @doctrine ]
