parameters:
    templating.globals.class: Core\CoreBundle\Component\Templating\GlobalVariables

    asgard.eventlistener.console.pid_file.class: Core\CoreBundle\EventListener\ConsolePidFileListener
    form.type.generic_entity.class: Core\CoreBundle\Form\Type\GenericEntityType

    message_helper.class: Core\CoreBundle\Component\Helper\MessageHelper

services:
    asgard.eventlistener.console.pid_file:
        class: %asgard.eventlistener.console.pid_file.class%
        arguments: [@monolog.logger]
        tags:
            - {name: kernel.event_listener, event: console.command, method: onConsoleCommand}
            - {name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate}

    form.type.generic_entity:
        class: %form.type.generic_entity.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: generic_entity }

    message_helper:
        class: %message_helper.class%
        arguments: [ @request_stack ]
