parameters:
    templating.globals.class: Core\CoreBundle\Component\Templating\GlobalVariables
    router.options.matcher_dumper_class: Core\CoreBundle\Component\Routing\Matcher\Dumper\PhpMatcherDumper
    router.options.generator_class: Core\CoreBundle\Component\Routing\Generator\UrlGenerator
    router.options.generator_base_class: Core\CoreBundle\Component\Routing\Generator\UrlGenerator

    event_subscriber.siteaccess.router.class: Core\CoreBundle\EventSubscriber\RouterSubscriber
    event_listener.console.pid_file.class: Core\CoreBundle\EventListener\ConsolePidFileListener
    form.type.generic_entity.class: Core\CoreBundle\Form\Type\GenericEntityType
    core.indexer.solr.class: Core\CoreBundle\Component\Indexer\SolrIndexer
    core.twig.extension.class: Core\CoreBundle\Twig\CoreCoreExtension;

services:
    monolog.logger.console:
        parent: monolog.logger_prototype
        arguments: { index_0: "console" }

    event_subscriber.siteaccess.router:
            class: %event_subscriber.siteaccess.router.class%
            arguments: [ @router, @?router.request_context, %asgard.siteaccesses% ]
            tags:
                - { name: kernel.event_subscriber }

    event_listener.console.pid_file:
        class: %event_listener.console.pid_file.class%
        arguments: [@monolog.logger]
        tags:
            - {name: kernel.event_listener, event: console.command, method: onConsoleCommand}
            - {name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate}

    form.type.generic_entity:
        class: %form.type.generic_entity.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: generic_entity }

    core.indexer.solr:
        class: %core.indexer.solr.class%
        arguments: [ %indexer.hostname%, %indexer.port%, %indexer.core% ]

    core.twig.extension:
        class: %core.twig.extension.class%
        arguments: []
        tags:
            - { name: twig.extension }
