parameters:
    templating.globals.class: Core\CoreBundle\Component\Templating\GlobalVariables

    asgard.eventlistener.console.pid_file.class: Core\CoreBundle\EventListener\ConsolePidFileListener
    form.type.entity.class: Core\CoreBundle\Form\Type\EntityType

services:
    asgard.eventlistener.console.pid_file:
        class: %asgard.eventlistener.console.pid_file.class%
        arguments: [@monolog.logger]
        tags:
            - {name: kernel.event_listener, event: console.command, method: onConsoleCommand}
            - {name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate}

    form.type.entity:
        class: %form.type.entity.class%
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: entity }