parameters:
    router.options.generator_class: Core\SearchBundle\Component\Routing\Generator\UrlGenerator
    router.options.generator_base_class: Core\SearchBundle\Component\Routing\Generator\UrlGenerator
    event_subscriber.search.router.class: Core\SearchBundle\EventSubscriber\RouterSubscriber
    form.type.search.class: Core\SearchBundle\Form\Type\SearchType
services:
    event_subscriber.search.router:
        class: '%event_subscriber.search.router.class%'
        arguments: [ '@router', '@?router.request_context' ]
        tags:
            - { name: kernel.event_subscriber }

    form.type.search:
        class: '%form.type.search.class%'
        arguments: [ '@request_stack', '@router' ]
        tags:
            - { name: form.type, alias: core_search }



#    search.type.solr:
#        class: %search.type.solr.class%
#        arguments: [ @monolog.logger, %searchengine.hostname%, %searchengine.port%, %searchengine.cores% ]
#        tags:
#            - { name: monolog.logger, channel: search }
#
#    search:
#        alias: search.type.solr
#
#    indexer.type.solr:
#        class: %indexer.type.solr.class%
#        arguments: [ @monolog.logger, %searchengine.hostname%, %searchengine.port%, %searchengine.cores% ]
#        tags:
#            - { name: monolog.logger, channel: index }
#
#    indexer:
#        alias: indexer.type.solr