parameters:
    form.type.search.class: Core\SearchBundle\Form\Type\SearchType

services:
    form.type.search:
        class: %form.type.search.class%
        arguments: [ @request_stack, @router ]
        tags:
            - { name: form.type, alias: core_search }
