parameters:
    form.type.search.class: Core\SearchBundle\Form\Type\SearchType

services:
    app.form.type.task:
        class: %form.type.search.class%
        tags:
            - { name: form.type, alias: core_search }
