display_tool_homepage:
    path:   /
    defaults: { _controller: DisplayBundle:Default:index }
    options:
        class: icon-camera
        label: Display

display_tool_admin:
    path:   /admin/
    defaults: { _controller: DisplayBundle:Admin:index }

