ezpublish_tool_homepage:
    path:     /
    defaults: { _controller: eZPublishBundle:Default:index }

ezpublish_right:
    path:     /right
    defaults: { _controller: eZPublishBundle:RightManagement:index }