parameters:
    ezpublish.form.type.role.class: eZPublishBundle\Form\Type\RoleType
    ezpublish.form.type.right.class: eZPublishBundle\Form\Type\RightType

services:
    ezpublish.form.type.role:
        class: %ezpublish.form.type.role.class%
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: ezpublish_role }

    ezpublish.form.type.right:
        class: %ezpublish.form.type.right.class%
        arguments: [ @ezpublish.form.type.role ]
        tags:
            - { name: form.type, alias: ezpublish_right }