parameters:
    ezpublish.form.type.role.class: eZPublishBundle\Form\Type\RoleType
    ezpublish.form.type.policy.class: eZPublishBundle\Form\Type\PolicyType

services:
    ezpublish.form.type.role:
        class: %ezpublish.form.type.role.class%
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: ezpublish_role }

    ezpublish.form.type.policy:
        class: %ezpublish.form.type.policy.class%
        tags:
            - { name: form.type, alias: ezpublish_policy }

    ezpublish.form.policy:
        class: eZPublishBundle\Form\PolicyType
        tags:
            - { name: form.type, alias: ezpublishbundle_policy }