LogTrackerBundle\Entity\LogFile:
    type: entity
    table: logfile
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        path:
            type: string
            length: 50
        mask:
            type: string
            length: 50

    manyToOne:
        link:
            targetEntity: Core\ProjectBundle\Entity\Link
            joinColumn:
                name: link_id
                referencedColumnName: id
