log_tracker_tool_homepage:
    path:   /
    defaults: { _controller: LogTrackerBundle:Default:index }
    options:
        class: icon-doc-text
        label: LogTracker

log_tracker_chart:
    path:   /chart/{query}
    defaults: { _controller: LogTrackerBundle:Default:chart, query: '*' }

log_tracker_search:
    path:   /search/{query}/{start}/{rows}
    defaults: { _controller: LogTrackerBundle:Default:search, query: '*', start: 0, rows: 10 }

log_tracker_data:
    path:   /data/{query}/{preventMonth}
    defaults: { _controller: LogTrackerBundle:Default:data, query: null, preventMonth: 6 }