log_tracker_tool_homepage:
    path:   /
    defaults: { _controller: LogTrackerBundle:Default:index }
    options:
        class: icon-doc-text
        label: LogTracker

log_tracker_view:
    path:   /view
    defaults: { _controller: LogTrackerBundle:Default:view }

log_tracker_search:
    path:   /search/{query}
    defaults: { _controller: LogTrackerBundle:Default:search, query: '*' }

log_tracker_data_error:
    path:   /dataerror
    defaults: { _controller: LogTrackerBundle:Default:viewDataError }