log_tracker_admin:
    path:     /
    defaults: { _controller: LogTrackerBundle:Admin:index }
    requirements:
        @siteaccess: admin

log_tracker_admin_logfile_edit:
    path:     /logfile/{id}
    defaults: { _controller: LogTrackerBundle:Admin:logfileEdit, id: null }
    requirements:
        @siteaccess: admin

log_tracker_admin_logfile_del:
    path:     /logfile/delete/{id}
    defaults: { _controller: LogTrackerBundle:Admin:logfileDelete, id: null }
    requirements:
        @siteaccess: admin

log_tracker_tool_homepage:
    path:   /
    defaults: { _controller: LogTrackerBundle:Default:index }
    options:
        class: icon-doc-text
        label: LogTracker

log_tracker_chart:
    path:   /chart/{query}/{preventMonth}
    defaults: { _controller: LogTrackerBundle:Default:chart, query: '*', preventMonth: 6 }
    requirements:
        preventMonth: "\d+"

log_tracker_search:
    path:   /search/{query}/{start}/{rows}
    defaults: { _controller: LogTrackerBundle:Default:search, query: '*', start: 0, rows: 10 }
    requirements:
        start: "\d+"
        rows: "\d+"

log_tracker_data:
    path:   /data/{query}/{preventMonth}
    defaults: { _controller: LogTrackerBundle:Default:data, query: null, preventMonth: 6 }
    requirements:
        preventMonth: "\d+"

log_tracker_view:
    path:   /view/{query}/{start}/{rows}
    defaults: { _controller: LogTrackerBundle:View:index, query: '*', start: 0, rows: 10, onlydata: false }
    requirements:
        start: "\d+"
        rows: "\d+"

log_tracker_view_onepage:
    path:   /viewdata/{query}/{start}/{rows}
    defaults: { _controller: LogTrackerBundle:View:index, query: '*', start: 0, rows: 10, onlydata: true }
    requirements:
        start: "\d+"
        rows: "\d+"