parameters:
    logfile_helper.class: LogTrackerBundle\Component\Helper\LogFileHelper

services:
    logfile_helper:
        class: %logfile_helper.class%
        arguments: [ @request_stack, @doctrine ]